import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  bookSidebar: [
    {
      type: 'category',
      label: 'Introduction',
      items: [
        'introduction/01-ros-2-overview',
        'introduction/02-digital-twin-overview',
        'introduction/03-isaac-perception-overview',
        'introduction/04-vla-capstone-overview',
      ],
    },
    {
      type: 'category',
      label: 'Module 1: The Robotic Nervous System',
      items: [
        'module-1/chapter-1',
        'module-1/chapter-2',
        'module-1/chapter-3',
      ],
    },
    {
      type: 'category',
      label: 'Module 2: The Digital Twin',
      items: [
        'module-2/chapter-1',
        'module-2/chapter-2',
        'module-2/chapter-3',
      ],
    },
    {
      type: 'category',
      label: 'Module 3: The AI-Robot Brain',
      items: [
        'module-3/chapter-1',
        'module-3/chapter-2',
        'module-3/chapter-3',
      ],
    },
    {
      type: 'category',
      label: 'Module 4: Vision-Language-Action',
      items: [
        'module-4/chapter-1',
        'module-4/chapter-2',
        'module-4/chapter-3',
      ],
    },
  ],
};

export default sidebars;
